name: publish

on:
  push:
    branches: [main, next, beta]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      
      - run: npm ci

      - name: Remove postinstall
        uses: sergeysova/jq-action@v2
        with:
          cmd: jq 'del(.scripts.postinstall) package.json'

      - name: Release Package
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_SECRET }}
        run: npx semantic-release
