name: storybook

on: 
  push:
    paths:
      - "src/**"
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          npm ci
          npm run build-storybook
      - name: Deploy Storybook
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BASE_BRANCH: main
          BRANCH: gh-pages
          FOLDER: docs-build
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: docs
